2024-08-17 16:25:00,935 - kedro.framework.project - INFO - Using 'conf\logging.yml' as logging configuration. You can change this by setting the KEDRO_LOGGING_CONFIG environment variable accordingly.
2024-08-17 16:25:02,336 - py.warnings - WARNING - C:\Users\benja\OneDrive\Escritorio\kedro\env\Lib\site-packages\kedro_viz\__init__.py:13: KedroVizPythonVersionWarning: Please be advised that Kedro Viz is not yet fully
        compatible with the Python version you are currently using.
  warnings.warn(

2024-08-17 16:25:05,088 - kedro.framework.cli.cli - ERROR - An error has occurred: No module named 'pyspark'
2024-08-17 16:25:05,090 - kedro_telemetry.plugin - INFO - Kedro is sending anonymous usage data with the sole purpose of improving the product. No personal data or IP addresses are stored on our side. If you want to opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment variables, or create a `.telemetry` file in the current working directory with the contents `consent: false`. Read more at https://docs.kedro.org/en/stable/configuration/telemetry.html
2024-08-25 11:36:18,051 - kedro.framework.project - INFO - Using 'conf\logging.yml' as logging configuration. You can change this by setting the KEDRO_LOGGING_CONFIG environment variable accordingly.
2024-08-25 11:36:18,840 - py.warnings - WARNING - C:\Users\benja\OneDrive\Escritorio\kedro\env\Lib\site-packages\kedro_viz\__init__.py:13: KedroVizPythonVersionWarning: Please be advised that Kedro Viz is not yet fully
        compatible with the Python version you are currently using.
  warnings.warn(

2024-08-25 11:36:20,746 - kedro_telemetry.plugin - INFO - Kedro is sending anonymous usage data with the sole purpose of improving the product. No personal data or IP addresses are stored on our side. If you want to opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment variables, or create a `.telemetry` file in the current working directory with the contents `consent: false`. Read more at https://docs.kedro.org/en/stable/configuration/telemetry.html
2024-08-25 11:42:41,121 - kedro.framework.project - INFO - Using 'conf\logging.yml' as logging configuration. You can change this by setting the KEDRO_LOGGING_CONFIG environment variable accordingly.
2024-08-25 11:42:41,848 - py.warnings - WARNING - C:\Users\benja\OneDrive\Escritorio\kedro\env\Lib\site-packages\kedro_viz\__init__.py:13: KedroVizPythonVersionWarning: Please be advised that Kedro Viz is not yet fully
        compatible with the Python version you are currently using.
  warnings.warn(

2024-08-25 11:42:43,529 - kedro.framework.cli.cli - ERROR - An error has occurred: No module named 'pyspark'
2024-08-25 11:42:43,531 - kedro_telemetry.plugin - INFO - Kedro is sending anonymous usage data with the sole purpose of improving the product. No personal data or IP addresses are stored on our side. If you want to opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment variables, or create a `.telemetry` file in the current working directory with the contents `consent: false`. Read more at https://docs.kedro.org/en/stable/configuration/telemetry.html
2024-08-25 11:43:41,095 - kedro.framework.project - INFO - Using 'conf\logging.yml' as logging configuration. You can change this by setting the KEDRO_LOGGING_CONFIG environment variable accordingly.
2024-08-25 11:43:41,879 - py.warnings - WARNING - C:\Users\benja\OneDrive\Escritorio\kedro\env\Lib\site-packages\kedro_viz\__init__.py:13: KedroVizPythonVersionWarning: Please be advised that Kedro Viz is not yet fully
        compatible with the Python version you are currently using.
  warnings.warn(

2024-08-25 11:43:43,613 - kedro.framework.cli.cli - ERROR - An error has occurred: No module named 'pyspark'
2024-08-25 11:43:43,615 - kedro_telemetry.plugin - INFO - Kedro is sending anonymous usage data with the sole purpose of improving the product. No personal data or IP addresses are stored on our side. If you want to opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment variables, or create a `.telemetry` file in the current working directory with the contents `consent: false`. Read more at https://docs.kedro.org/en/stable/configuration/telemetry.html
2024-08-25 11:45:22,016 - kedro.framework.project - INFO - Using 'conf\logging.yml' as logging configuration. You can change this by setting the KEDRO_LOGGING_CONFIG environment variable accordingly.
2024-08-25 11:45:22,750 - py.warnings - WARNING - C:\Users\benja\OneDrive\Escritorio\kedro\env\Lib\site-packages\kedro_viz\__init__.py:13: KedroVizPythonVersionWarning: Please be advised that Kedro Viz is not yet fully
        compatible with the Python version you are currently using.
  warnings.warn(

2024-08-25 11:45:24,350 - kedro.framework.cli.cli - ERROR - An error has occurred: No module named 'pyspark'
2024-08-25 11:45:24,352 - kedro_telemetry.plugin - INFO - Kedro is sending anonymous usage data with the sole purpose of improving the product. No personal data or IP addresses are stored on our side. If you want to opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment variables, or create a `.telemetry` file in the current working directory with the contents `consent: false`. Read more at https://docs.kedro.org/en/stable/configuration/telemetry.html
2024-08-25 11:48:00,597 - kedro.framework.project - INFO - Using 'conf\logging.yml' as logging configuration. You can change this by setting the KEDRO_LOGGING_CONFIG environment variable accordingly.
2024-08-25 11:48:01,447 - py.warnings - WARNING - C:\Users\benja\OneDrive\Escritorio\kedro\env\Lib\site-packages\kedro_viz\__init__.py:13: KedroVizPythonVersionWarning: Please be advised that Kedro Viz is not yet fully
        compatible with the Python version you are currently using.
  warnings.warn(

2024-08-25 11:48:04,251 - kedro.framework.session.session - INFO - Kedro project league-of-legends
2024-08-25 11:48:08,100 - py.warnings - WARNING - C:\Users\benja\OneDrive\Escritorio\kedro\env\Lib\site-packages\kedro\framework\project\__init__.py:426: UserWarning: An error occurred while importing the 'league_of_legends.pipelines.process_raw_data' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "C:\Users\benja\OneDrive\Escritorio\kedro\env\Lib\site-packages\kedro\framework\project\__init__.py", line 418, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\benja\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\benja\OneDrive\Escritorio\kedro\league-of-legends\src\league_of_legends\pipelines\process_raw_data\__init__.py", line 6, in <module>
    from .pipeline import create_pipeline
  File "C:\Users\benja\OneDrive\Escritorio\kedro\league-of-legends\src\league_of_legends\pipelines\process_raw_data\pipeline.py", line 7, in <module>
    from .nodes import load_arff_dataset, transform_data
ImportError: cannot import name 'load_arff_dataset' from 'league_of_legends.pipelines.process_raw_data.nodes' (C:\Users\benja\OneDrive\Escritorio\kedro\league-of-legends\src\league_of_legends\pipelines\process_raw_data\nodes.py)

  warnings.warn(

2024-08-25 11:48:08,288 - kedro.framework.cli.cli - ERROR - An error has occurred: Pipeline contains no nodes after applying all provided filters
2024-08-25 11:48:08,290 - kedro_telemetry.plugin - INFO - Kedro is sending anonymous usage data with the sole purpose of improving the product. No personal data or IP addresses are stored on our side. If you want to opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment variables, or create a `.telemetry` file in the current working directory with the contents `consent: false`. Read more at https://docs.kedro.org/en/stable/configuration/telemetry.html
2024-08-25 11:54:45,216 - kedro.framework.project - INFO - Using 'conf\logging.yml' as logging configuration. You can change this by setting the KEDRO_LOGGING_CONFIG environment variable accordingly.
2024-08-25 11:54:45,575 - py.warnings - WARNING - C:\Users\benja\OneDrive\Escritorio\kedro\env\Lib\site-packages\kedro_viz\__init__.py:13: KedroVizPythonVersionWarning: Please be advised that Kedro Viz is not yet fully
        compatible with the Python version you are currently using.
  warnings.warn(

2024-08-25 11:54:47,810 - kedro.framework.session.session - INFO - Kedro project league-of-legends
2024-08-25 11:54:51,175 - py.warnings - WARNING - C:\Users\benja\OneDrive\Escritorio\kedro\env\Lib\site-packages\kedro\framework\project\__init__.py:426: UserWarning: An error occurred while importing the 'league_of_legends.pipelines.process_raw_data' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "C:\Users\benja\OneDrive\Escritorio\kedro\env\Lib\site-packages\kedro\framework\project\__init__.py", line 418, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\benja\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\benja\OneDrive\Escritorio\kedro\league-of-legends\src\league_of_legends\pipelines\process_raw_data\__init__.py", line 6, in <module>
    from .pipeline import create_pipeline
  File "C:\Users\benja\OneDrive\Escritorio\kedro\league-of-legends\src\league_of_legends\pipelines\process_raw_data\pipeline.py", line 7, in <module>
    from .nodes import load_arff_dataset, transform_data
ImportError: cannot import name 'load_arff_dataset' from 'league_of_legends.pipelines.process_raw_data.nodes' (C:\Users\benja\OneDrive\Escritorio\kedro\league-of-legends\src\league_of_legends\pipelines\process_raw_data\nodes.py)

  warnings.warn(

2024-08-25 11:54:51,324 - kedro.framework.cli.cli - ERROR - An error has occurred: Pipeline contains no nodes after applying all provided filters
2024-08-25 11:54:51,326 - kedro_telemetry.plugin - INFO - Kedro is sending anonymous usage data with the sole purpose of improving the product. No personal data or IP addresses are stored on our side. If you want to opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment variables, or create a `.telemetry` file in the current working directory with the contents `consent: false`. Read more at https://docs.kedro.org/en/stable/configuration/telemetry.html
2024-08-25 11:55:39,047 - kedro.framework.project - INFO - Using 'conf\logging.yml' as logging configuration. You can change this by setting the KEDRO_LOGGING_CONFIG environment variable accordingly.
2024-08-25 11:55:39,416 - py.warnings - WARNING - C:\Users\benja\OneDrive\Escritorio\kedro\env\Lib\site-packages\kedro_viz\__init__.py:13: KedroVizPythonVersionWarning: Please be advised that Kedro Viz is not yet fully
        compatible with the Python version you are currently using.
  warnings.warn(

2024-08-25 11:55:41,706 - kedro.framework.session.session - INFO - Kedro project league-of-legends
2024-08-25 11:55:46,605 - py.warnings - WARNING - C:\Users\benja\OneDrive\Escritorio\kedro\env\Lib\site-packages\kedro\framework\project\__init__.py:426: UserWarning: An error occurred while importing the 'league_of_legends.pipelines.process_raw_data' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "C:\Users\benja\OneDrive\Escritorio\kedro\env\Lib\site-packages\kedro\framework\project\__init__.py", line 418, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\benja\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\benja\OneDrive\Escritorio\kedro\league-of-legends\src\league_of_legends\pipelines\process_raw_data\__init__.py", line 6, in <module>
    from .pipeline import create_pipeline
  File "C:\Users\benja\OneDrive\Escritorio\kedro\league-of-legends\src\league_of_legends\pipelines\process_raw_data\pipeline.py", line 7, in <module>
    from .nodes import load_arff_dataset, transform_data
ImportError: cannot import name 'transform_data' from 'league_of_legends.pipelines.process_raw_data.nodes' (C:\Users\benja\OneDrive\Escritorio\kedro\league-of-legends\src\league_of_legends\pipelines\process_raw_data\nodes.py)

  warnings.warn(

2024-08-25 11:55:46,756 - kedro.framework.cli.cli - ERROR - An error has occurred: Pipeline contains no nodes after applying all provided filters
2024-08-25 11:55:46,758 - kedro_telemetry.plugin - INFO - Kedro is sending anonymous usage data with the sole purpose of improving the product. No personal data or IP addresses are stored on our side. If you want to opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment variables, or create a `.telemetry` file in the current working directory with the contents `consent: false`. Read more at https://docs.kedro.org/en/stable/configuration/telemetry.html
2024-08-25 11:56:37,138 - kedro.framework.project - INFO - Using 'conf\logging.yml' as logging configuration. You can change this by setting the KEDRO_LOGGING_CONFIG environment variable accordingly.
2024-08-25 11:56:37,513 - py.warnings - WARNING - C:\Users\benja\OneDrive\Escritorio\kedro\env\Lib\site-packages\kedro_viz\__init__.py:13: KedroVizPythonVersionWarning: Please be advised that Kedro Viz is not yet fully
        compatible with the Python version you are currently using.
  warnings.warn(

2024-08-25 11:56:39,758 - kedro.framework.session.session - INFO - Kedro project league-of-legends
2024-08-25 11:56:43,702 - kedro.framework.cli.cli - ERROR - An error has occurred: An exception occurred when parsing config for dataset 'raw_arff_dataset':
Class 'kedro.extras.datasets.text.TextDataSet' not found, is this a typo?
Hint: If you are trying to use a dataset from `kedro-datasets`>=2.0.0, make sure that the dataset name uses the `Dataset` spelling instead of `DataSet`.
2024-08-25 11:56:43,704 - kedro_telemetry.plugin - INFO - Kedro is sending anonymous usage data with the sole purpose of improving the product. No personal data or IP addresses are stored on our side. If you want to opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment variables, or create a `.telemetry` file in the current working directory with the contents `consent: false`. Read more at https://docs.kedro.org/en/stable/configuration/telemetry.html
2024-08-25 11:57:54,040 - kedro.framework.project - INFO - Using 'conf\logging.yml' as logging configuration. You can change this by setting the KEDRO_LOGGING_CONFIG environment variable accordingly.
2024-08-25 11:57:54,408 - py.warnings - WARNING - C:\Users\benja\OneDrive\Escritorio\kedro\env\Lib\site-packages\kedro_viz\__init__.py:13: KedroVizPythonVersionWarning: Please be advised that Kedro Viz is not yet fully
        compatible with the Python version you are currently using.
  warnings.warn(

2024-08-25 11:57:56,652 - kedro.framework.session.session - INFO - Kedro project league-of-legends
2024-08-25 11:58:00,378 - kedro_telemetry.plugin - INFO - Kedro is sending anonymous usage data with the sole purpose of improving the product. No personal data or IP addresses are stored on our side. If you want to opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment variables, or create a `.telemetry` file in the current working directory with the contents `consent: false`. Read more at https://docs.kedro.org/en/stable/configuration/telemetry.html
2024-08-25 11:58:00,967 - kedro.runner.sequential_runner - INFO - Using synchronous mode for loading and saving data. Use the --async flag for potential performance gains. https://docs.kedro.org/en/stable/nodes_and_pipelines/run_a_pipeline.html#load-and-save-asynchronously
2024-08-25 11:58:00,970 - kedro.io.data_catalog - INFO - Loading data from raw_arff_dataset (TextDataset)...
2024-08-25 11:58:00,972 - kedro.runner.sequential_runner - WARNING - No nodes ran. Repeat the previous command to attempt a new run.
2024-08-25 11:58:01,129 - kedro.framework.cli.cli - ERROR - An error has occurred: Failed while loading data from data set TextDataset(filepath=C:/Users/benja/OneDrive/Escritorio/kedro/league-of-legends/data/01_raw/dataset.arff, protocol=file).
[Errno 2] No such file or directory: 'C:/Users/benja/OneDrive/Escritorio/kedro/league-of-legends/data/01_raw/dataset.arff'
2024-08-25 12:04:48,177 - kedro.framework.project - INFO - Using 'conf\logging.yml' as logging configuration. You can change this by setting the KEDRO_LOGGING_CONFIG environment variable accordingly.
2024-08-25 12:04:48,581 - py.warnings - WARNING - C:\Users\benja\OneDrive\Escritorio\kedro\env\Lib\site-packages\kedro_viz\__init__.py:13: KedroVizPythonVersionWarning: Please be advised that Kedro Viz is not yet fully
        compatible with the Python version you are currently using.
  warnings.warn(

2024-08-25 12:04:50,994 - kedro.framework.session.session - INFO - Kedro project league-of-legends
2024-08-25 12:04:54,936 - kedro_telemetry.plugin - INFO - Kedro is sending anonymous usage data with the sole purpose of improving the product. No personal data or IP addresses are stored on our side. If you want to opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment variables, or create a `.telemetry` file in the current working directory with the contents `consent: false`. Read more at https://docs.kedro.org/en/stable/configuration/telemetry.html
2024-08-25 12:04:55,526 - kedro.runner.sequential_runner - INFO - Using synchronous mode for loading and saving data. Use the --async flag for potential performance gains. https://docs.kedro.org/en/stable/nodes_and_pipelines/run_a_pipeline.html#load-and-save-asynchronously
2024-08-25 12:04:55,529 - kedro.io.data_catalog - INFO - Loading data from raw_arff_dataset (TextDataset)...
2024-08-25 12:04:55,531 - kedro.runner.sequential_runner - WARNING - No nodes ran. Repeat the previous command to attempt a new run.
2024-08-25 12:04:55,685 - kedro.framework.cli.cli - ERROR - An error has occurred: Failed while loading data from data set TextDataset(filepath=C:/Users/benja/OneDrive/Escritorio/kedro/league-of-legends/data/01_raw/dataset.arff, protocol=file).
[Errno 2] No such file or directory: 'C:/Users/benja/OneDrive/Escritorio/kedro/league-of-legends/data/01_raw/dataset.arff'
2024-08-25 12:05:45,311 - kedro.framework.project - INFO - Using 'conf\logging.yml' as logging configuration. You can change this by setting the KEDRO_LOGGING_CONFIG environment variable accordingly.
2024-08-25 12:05:45,682 - py.warnings - WARNING - C:\Users\benja\OneDrive\Escritorio\kedro\env\Lib\site-packages\kedro_viz\__init__.py:13: KedroVizPythonVersionWarning: Please be advised that Kedro Viz is not yet fully
        compatible with the Python version you are currently using.
  warnings.warn(

2024-08-25 12:05:47,896 - kedro.framework.session.session - INFO - Kedro project league-of-legends
2024-08-25 12:05:51,637 - kedro_telemetry.plugin - INFO - Kedro is sending anonymous usage data with the sole purpose of improving the product. No personal data or IP addresses are stored on our side. If you want to opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment variables, or create a `.telemetry` file in the current working directory with the contents `consent: false`. Read more at https://docs.kedro.org/en/stable/configuration/telemetry.html
2024-08-25 12:05:52,243 - kedro.runner.sequential_runner - INFO - Using synchronous mode for loading and saving data. Use the --async flag for potential performance gains. https://docs.kedro.org/en/stable/nodes_and_pipelines/run_a_pipeline.html#load-and-save-asynchronously
2024-08-25 12:05:52,246 - kedro.io.data_catalog - INFO - Loading data from raw_arff_dataset (TextDataset)...
2024-08-25 12:05:52,655 - kedro.pipeline.node - INFO - Running node: load_and_clean_arff_data: load_arff_dataset([raw_arff_dataset]) -> [cleaned_dataset]
